### PR TITLE
Remove modsulator dependency

### PR DESCRIPTION
**Pull request by cbeer**
See https://github.com/sul-dlss/dor-services/issues/180

### CODE REVIEW

**Comment by cbeer** [comment]
Sorry, I think that context got lost when switching from `develop` to `master` (see #181)

> This copies the only the relevant normalization from modsulator into a Dor::Utils::Normalizer class. @tingulfsen and I discussed alternatives (including copying normalizer into a separate gem), but we agreed the similarity is relatively trivial and may not be worth doing.

The main reason to break the dependency is we really shouldn't drag in all of modsulator's dependencies (including some heavy-weight ones like `roo`) just to clean up some rights XML. It's especially confusing because Modsulator's Normalizer class has really been set up to handle MODS.

We certainly could make a brand new gem with just this class. I'd suggest we wait until we have some other consumer or find these classes are changing before bothering with the overhead. There's a separate question to discover what is producing bad rights metadata and just fix it.

**Comment by drh-stanford** [comment]
@tingulfsen i agree with @atz and propose that we extract the pure XML normalization into a `Normalizer` gem (rather than calling it `Modsulator::Utils`) as it would be a place to put our normailzation code -- beyond MODS and RightsMetadata, which is what it covers now. Dor services already has lots of code bloat and it'd be nice to keep the duplicate code out.

Re: producting bad rights metadata -- it's users who can type in randomly weird XML into the rightsMetadata editor in Argo. The editor validates the user-entered XML but does not normalize it (it's in JavaScript -- see https://github.com/sul-dlss/argo/blob/master/app/assets/javascripts/modules/datastream_edit.js#L9)

**Comment by LynnMcRae** [comment]
MODS Normalization was specified to be its own separate service (see https://consul.stanford.edu/display/chimera/MODS+bulk+loading) callable by Modsulator but able to be independently invoked, including a web service call. I don't know if we actually have that, but making it generic is a good thing, more valuable than a MODS-only normalizer, even if it retains some small extra knowledge of MODS.  I'd like to have the Normalization page on consul properly reflect the more generic capability. I'll work with @tingulfsen on that if he's tracking it.

**Comment by ndushay** [comment]
@tingulfsen is this addressed by #209 ?

**Comment by jcoyne** [comment]
Superseded by #344

**Pull request closed without merging**
