### PR TITLE
use https for logo URL for 4.x

### PR DESCRIPTION
**Pull request by drh-stanford**
see https://github.com/sul-dlss/dor-services/pull/75 for discussion

### CODE REVIEW

**Comment by drh-stanford** [comment]
@atz @jmartin-sul are the builds broken on the 4.x branch? They are failing when trying to pull down gems... maybe it's spurious?

**Comment by atz** [comment]
Build errors on old rubies for non-production dependency `debugger`.

**Comment by atz** [comment]
After my revision of the Gemfile, can somebody determine why Travis (building under :test grouping, right?) is even trying to install debugger in the first place?  How is this dependency even being hit?

**Comment by drh-stanford** [comment]
I was having problems with ruby versions. The debugger is keyed only to Ruby 1.9.x(?).

  https://github.com/sul-dlss/dor-services/blob/4.x/Gemfile#L7

**Comment by atz** [comment]
Yeah, that's because debugger doesn't support ruby 2.x.  Most of these debugger/dev tools are still not developer dependencies, strictly speaking, and needn't be in our Gemspec.  In particular, stuff like `awesome_print` isn't even invoked anywhere, yet it is still required.  So I cleaned up spec_helper on 4.x.  Build is green there now, so rebase and PR away!

**Pull request merged**
