### PR TITLE
use https for logo URL

### PR DESCRIPTION
**Pull request by drh-stanford**
this is for the IIIF manifest's logo attribute

### CODE REVIEW

**Comment by drh-stanford** [comment]
@mejackreed can you take a look at this? we want to change the logo URLs in the IIIF manifest to https.

**Comment by mejackreed** [comment]
:+1: looks good to me. Let me know if you want me to merge it

**Comment by drh-stanford** [comment]
This needs to be merged into the 4.x branch

**Comment by atz** [comment]
Closing this, PR should not be made from topic to master.  Targets should include `4.x` (as you already have) and `develop`.

**Pull request closed without merging**
