### PR TITLE
provide for setting empty copyright/uses and normalize defaultObjectRights XML

### PR DESCRIPTION
**Pull request by drh-stanford**
…ights XML. this includes the XML normalization code from the modsulator. 

Partially addresses Argo issue https://github.com/sul-dlss/argo/issues/70

### CODE REVIEW

**Comment by drh-stanford** [comment]
@tingulfsen please review this integration of the modsulator into dor-services. i'm using it on the defaultObjectRights datastream (in the rightsMetadata schema, not mods).

**Comment by atz** [comment]
I'm not sure this can be cleanly picked over to `4.x`.  It seems to require several earlier commits including the `CREATIVE_COMMONS_USE_LICENSES` style variable declarations in Editable.  Even with those added, some 12 rspec errors are introduced with the pick.  Unless there is a specific `4.x` consumer that needs this, I think we should mark it as a point of divergence.

**Comment by drh-stanford** [comment]
I think `develop` only is fine.

**Comment by tingulfsen** [comment]
@drh-stanford sorry for the delay. I actually discovered an unrelated bug withing the MODSulator...arghhh...but I will get to the refactoring you require today and put forth a pull request for you to look at.

**Pull request merged**
