### PR TITLE
4.x: expand isConstituentOf into MODS relation for publicObject

### PR DESCRIPTION
**Pull request by drh-stanford**
See JUMBO-18 for details. 

This code still needs testing. Unfortunately, the MODS expansion code that turns relations into relatedItems does not have tests. It's stubbed out so that the code is not run. See: https://github.com/sul-dlss/dor-services/blob/4.x/spec/dor/publishable_spec.rb#L61 for where the existing expansion code is stubbed out -- that code expands isMemberOfCollection relations into the appropriate MODS...

### CODE REVIEW

**Comment by drh-stanford** [comment]
I've added unit tests now.

**Comment by atz** [comment]
Please squash to remove the needless conflict commit/removal.

**Comment by drh-stanford** [comment]
i squashed the commits.

**Comment by atz** [comment]
Please confirm whether forward-port is needed to `develop`.

**Comment by atz** [comment]
Ported to `develop`.

**Pull request merged**
