### PR TITLE
Fix collection reference 404

### PR DESCRIPTION
**Pull request by jmartin-sul**
refactoring in small-ish increments, as seen in the commit history, then bug fixed in the last commit.

this assumes that we want to create a `relatedItem` node even if the reference is to a non-existent collection (in which case this change just stored the druid where it would store the collection name, a la the indexing behavior).  if we just want to not create a `relatedItem` node in these situations, that's easy enough also.  @LynnMcRae?

### CODE REVIEW

**Comment by drh-stanford** [comment]
I'm :+1: for this PR. It's still marked [WIP] though...

**Comment by LynnMcRae** [comment]
@jmartin-sul : a bad collection reference is bad data no matter how you slice it, so my first instinct was to skip creating a relatedItem in the MODS and not create a link to nowhere. On the other hand a Collection title that is a druid will be noticed and fixed vs absent data that might go unnoticed ... but I'm still with the first option (no relatedItem) if that is as easy as the other, given we're talking about public data. @blalbrit do you agree?

**Comment by blalbrit** [comment]
+1 @LynnMcRae

**Comment by jmartin-sul** [comment]
ok, will change to not write it in that case...

**Comment by jmartin-sul** [comment]
fixed

**Pull request merged**
